### ISSUE TITLE
web site and documentation

### ISSUE THREAD

**Issue by vsoch** [openbases/docs#3]
The documentation / website for the templates will eventually live here, so we need a nice generation strategy. @FelixHenninger I really like what you have for LabJS, and actually @jodeleeuw yours too! Should we start with a variation on that?

**Comment by vsoch** [comment]
feedback wanted! I am working with https://docs.cornerstonejs.org and I consistently find myself thinking "I really like this documentation!" Well it' just this thing called "gitbook" --> https://www.gitbook.com/

Have you guys tried this out, and / or would be open to giving it a try? In that it's integrated with Github, and (the other thing I started working on) is sphinx (and this isn't super friendly if you don't know how to program) I think it might be a good option for us.

**Comment by vsoch** [comment]
oh eww, 2 users for free, maybe not :P 
![image](https://user-images.githubusercontent.com/814322/44631948-41666c80-a941-11e8-90d4-e11f3057f977.png)

**Comment by jodeleeuw** [comment]
I've been happy with [mkdocs](https://github.com/mkdocs/mkdocs/) (what I use for jspsych). Everything is markdown, so it's very easy for the community to edit docs and submit PRs.

**Comment by vsoch** [comment]
oh cool! Let me check that one out - I really like your new docs too :) We definitely need a good balance of renders beautifully, but also is easy to contribute to.

**Comment by vsoch** [comment]
oh I really like this! :)

**Comment by vsoch** [comment]
Just for color reference --> https://www.materialui.co/colors
